Fix another new python2.7 error
SyntaxError: encoding declaration in Unicode string
We need to remove coding cookies from initial_data.py and fix umlaut
characters to the utf-8 representation.