Bug-Fix
More than two supervisors selected in user search mask cause a backtrace
with
"exceptions.AttributeError: 'list' object has no attribute 'value'"
reported by MPA.